### ISSUE TITLE
CI環境の環境変数とdockerファイルの環境変数を統一する

### ISSUE THREAD

**Issue by koba-masa** [koba-masa/rails_dev_env#6]

**Comment by koba-masa** [comment]
```
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_HOST: 127.0.0.1
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres123
```
